branches:
  only:
  - master
deploy:
  provider: s3
  bucket: makeuc.io
  skip_cleanup: true
  region: us-east-2
  on:
    branch: master
  dot_match: true
  access_key_id:
    secure: P9dq9du+aySVE+GVYkpa4qgVY6cjLkvkFddyx4ImRhaeUICWIczP9rX4bUiJYdomX0jEBXaM+TT4fb/s/7jIubIHLWt9WhyCSOo1OIBgu5jWrkK8BCGoHUms9/tnLz8JmsDbGKVPCt4lGa/Ij7h2yDq0Iu4Zrx/ywdPgmtlrD8HHMFqafoK6aBOQQ/iGfI25B2GCpkCWyLYsSQFO+jEGQ6YkG47f4zWE8Bfw4rixSklhIWjXyqaEoKKdzF8gRqI44OwXEwsn1B6itPROIL3clEiajfiGCz+fRBC4V8/g+lylDuDqMx2rJAaJKWin7ha0eYlfikVdvUcmURob4Uk7E7kaQ+GI6or5aKBNqyUxzcZ4HP2YXNDSkxiaTRJ944bSfN4q8BUJGnPr7vlgV647H1lw7xHLkFCA+z6NUayu6s4HAd/AlvjyGC7IJjTRllyVNouzMPrGk2jQs6h7mT0JOBrnSbRM+oSP5/AgjilmtRsUMQc/PcC+hhOLITLPtUenRXg+CPYEuVcPOlGQtJN6JWHbYSjf5vVz/FZGy2/aSVGN+1HKoh/6EUnjWKjqSbaaKM+H97JJ16jD8OpJcvJIPGNNatF/8wtKLfb/3dmll+ZVfI1Lh3wQ8f1vtHjF7CLG8/NSQnhncpOqP0ij3/ivYMhcYEmuxuBCas5fl27PqZI=
  secret_access_key:
    secure: TdSNGBAInOLn60D4jzzdCzx69j+BDn414xRgjCw0NwufImk0FSPUgS9DC+4ADaxXC/PwSMthCHrRzpHuA+FH9CE/k+PG4EybVmPTLW7mSO96W1p9T5pJWgUVEfBTS6yKJM+pjtW+JpRpOSh4NDuB6IbIFNRhMkgngp5VtEDNnyYpHJ9Uh9kBqXzuMw8OVIPJyUWaLRB/Lwsze+eIkwPTqx7abcWjyHlaLe8TtoWXI0s923x2n0BOuQ+weey9ZhQLlz3fMVzpUjhYufbwkzKMoQdXZ5h6aFVN/FzlOvZEshZGLrXhCdlWAHcdjufzpEUoyFkGlCvlghTG1oAaD8M0v6HBSfi7mXM8iKnYmMTop11/w3GF1pG2cwcXfItbKkEYx6D02dZqQs75P4jmg5XNZrVEdd0Y2vcueVoc4Ht1LG6Mlgahbz0Xz6320CSvRR5q2sc+h4Rj5Zlbtrh7ZvVsQl+B1eedCSqE0O1EwVi8ECVTQ0w5o23EUXVmGoDbDFzihkv2uU23QGFx9zoh/rm3UVDFme267k3R+WMxzkV4kw3Nf9kz7PiHtzGVRwLAYDYiZzGs/fylAsqseILu9/DDu8jW3GAoDEV0xUaEGtUlHMQusjZ9IlOQ3IVHby0mbRHaF6Vvjjuj7I8oivRjj0QCvsFYFl5dlcCCXBQl9KNlKJc=
